### ISSUE TITLE
consider including working example(s)

### ISSUE THREAD

**Issue by tmc** [shurcooL/trayhost#7]
Working minimal examples would help illustrate the use of this package.

**Comment by shurcooL** [comment]
Sounds like a good idea, I will do that.

Until this is resolved, feel free to look at Instant Share client [source](https://github.com/pavben/InstantShare/blob/c72060a1043bb7727b27f37eae2805b28239e0ad/client/main.go#L151-L184), which uses this package.

**Comment by shurcooL** [comment]
Done. See http://godoc.org/github.com/shurcooL/trayhost#example-package.

**Comment by jacobrosenthal** [comment]
Hrm. Trying this now but unsuccessful. Added the plist, an icon, changed name of the CFBundleExecutable, but when I click nothing happens. The only thing in the console is a ```quicklooksattelite: no file data for file file:///something.app```

**Comment by shurcooL** [comment]
Which icon did you add? The example mentions `"app-icon@2x.png"`, which needs to be in the `Resources` folder. There's also `Icon.icns` which is for the app bundle icon.

**Comment by jacobrosenthal** [comment]
Thanks for the response. Both actually. Im also playing with the Instant Share app you linked above.

**Comment by jacobrosenthal** [comment]
Is there some naming that has to match, inside the go app and in the plist, etc? Is there some logging I can add? Im actually not that familiar with go otherwise.

**Comment by shurcooL** [comment]
Thanks for the reproduce case in #8. With that, I was able to reproduce the issue and I now know what's wrong.

The problem was that by default, when launched via Finder, an app bundle will have its working directory at root (`/`) instead of inside the app bundle's Resources directory.

The reason it worked for my Instant Share.app is because I had the following bash script inside, which was executed first:

```bash
#!/bin/bash

WD=$(dirname "$0")
cd "${WD}/../Resources"
../MacOS/main -flags -here >log.txt 2>&1
```

I named that script `wd` and pointed it as the executable to run in the `Info.plist` file:

```XML
<key>CFBundleExecutable</key>
<string>wd</string>
```

So, that answers the question of how to logging (and specify flags, if you want).

I definitely did not document this part in the example, so I need to fix that.
